### ISSUE TITLE
Move getting the changelog to a netlify function?

### ISSUE THREAD

**Issue by Noviny** [Thinkmill/changelogs-xyz#2]
I literally have no opinions one way or another, other than this is fun, but maybe? What are actual pros + cons

**Comment by mitchellhamilton** [comment]
I can't think of any pros and the immediate con I see is complexity

**Comment by rohan-deshpande** [comment]
I think this should be reopened. I see huge value in "Changelogs as a service" and this will enable that. Take this situation as an example 

- I have a product
- I have a website for the product 
- They are in separate repos (maybe in different languages altogether)
- I want a page on the website `/release-notes` that fires an API request to some endpoint to get the markdown contents of `CHANGELOG.md` for the product
- I can render those contents on my website any way I like

This really unlocks the potential for CaaS for your app imo. Consumers can get great value because they can point their customers/users to a consistent place that is on brand and has the latest updates. It also saves you from having to have a "theming" feature, because if people want custom themes/domains they can just use the API.

**Comment by Noviny** [comment]
Is your product publicly published on npm btw?

**Comment by rohan-deshpande** [comment]
That was just an example, my specific use case might be a little different. As my particular product is closed source, I would probably host a public facing`CHANGELOG.md` in a different repo but it be kept in sync with my closed source repo via ci
